spring.application.name=motor-procesos

#Puerto
server.port=${SERVER_PORT:5041}
server.servlet.context-path=/API/tesis

#Rutas de consumo
correo.url=${CORREO_URL:http://localhost:8282/API/tesis/}
corsorigin.url=${CORSORIGIN_URL:http://localhost:4200}


#Coneccion Base
#spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/base_tesis}
#spring.datasource.username=${POSTGRES_USER:postgres}
#spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://tesis-lm-p}
spring.datasource.username=${POSTGRES_USER:pogres}
spring.datasource.password=${POSTGRES_PASSWORD:poses}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.enabled=false

# Habilitar balanceo de carga
spring.cloud.discovery.enabled=false

#Motor de procesos
flowable.rest.enabled=true
flowable.actuator.enabled=true

#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.info.build.enabled=true

