spring.application.name=motor-procesos

server.port=${SERVER_PORT:5041}
server.servlet.context-path=/API/tesis
correo.url=${CORREO_URL:http://correo:8080/API/tesis/}

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/flowable_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.enabled=false

# Habilitar balanceo de carga
spring.cloud.discovery.enabled=false

#Puerto

flowable.rest.enabled=true
flowable.actuator.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.info.build.enabled=true